### ISSUE TITLE
Migrate from figaro to dotenv-rails

### ISSUE THREAD

**Issue by coorasse** [renuo/applications-setup-guide#151]
Figaro is not supported anymore (although it still works). This issue opens the discussion to migrate to the maintained dotenv-rails.

**Comment by coorasse** [comment]
What I see as a problem, is the configuration of env specific values

**Comment by schmijos** [comment]
Would it be an option to take over the project, or at least keep on working on our branch? Figaro is pretty small. What I'd also consider is the new way Rails handles the secrets. We'll not have secret ENVs anyways in the future.

**Comment by coorasse** [comment]
Two points against Rails credentials:
* you cannot configure different credentials for testing, develop, and master. You would need to create three equivalent Rails environments, which at the moment we don't have (we use production in all three)
* IMHO it goes against this 12 factor app principle of keeping configuration in the environment: https://12factor.net/config

**Comment by coorasse** [comment]
Regarding Figaro maintainance, I'd be in. Could you try to get in touch with @laserlemon and see if he is interested in adding us as maintainers?
Maybe releasing a figaro2 gem would be an option as well

**Comment by coorasse** [comment]
I just noticed v2 is on the way: https://github.com/laserlemon/figaro/tree/v2

**Comment by coorasse** [comment]
closing as stale
