### ISSUE TITLE
Deprecate NewRelic

### ISSUE THREAD

**Issue by coorasse** [renuo/applications-setup-guide#154]
Discussion regarding if we want to keep NewRelic or not in our applications

**Comment by coorasse** [comment]
In the last week I noticed once again how important is NewRelic to identify bottlenecks. In schuler we had really big performance issue and NewRelic pointed me directly to the problem, therefore I would suggest to not deprecate NewRelic if an alternative is not provided.

**Comment by coorasse** [comment]
@schmijos I wrote my inputs in this issue. Could you elaborate further your point of view since you suggested to deprecate NewRelic?

**Comment by schmijos** [comment]
If it is the case that we sometimes need NewRelic, why not install it when needed? If this performance monitoring Martin suggested is coming, then I'm in to keep it. But frankly: now for most projects it's just in vain.

**Comment by coorasse** [comment]
I close this discussion since it didn't proceed for more than a year. Please re-open in case something pops out.

**Comment by Liberatys** [comment]
Some of my findings looking into this:

**Findings**:

    New Relic has moved a lot of settings that we use to be the default
    They also introduced browser monitoring which seems to be a tool to monitor the user experience and the latency and other parameters on the client side.

We could strip down the configuration by about half. A lot of boolean values we set are default and thus not needed. But this would prompt us to monitor updates to New Relic and their default configuration and alter our configuration accordingly.
