### ISSUE TITLE
Broken / Outdated links in setup guide

### ISSUE THREAD

**Issue by Liberatys** [renuo/applications-setup-guide#240]
Currently there are broken / outdated links in the [ruby on rails](https://github.com/renuo/applications-setup-guide/tree/master/ruby_on_rails) setup guide: 

* **Rack CORS**
* **Rack Attack**

I'd suggest to either remove the two or link them to their respective GitHub repository(if needed).

**Comment by schmijos** [comment]
Gogogo! You can propose a PR directly for such matters.
