### ISSUE TITLE
bin/setup: more transparent

### ISSUE THREAD

**Issue by sihu** [renuo/applications-setup-guide#52]
for decisions, the user could/should make himself, i would like to introduce a command prompt (e.g. https://github.com/JEG2/highline) to let the user know, what the system would do for him. so it's up for the user, if he wants the let the bin/setup change system things. especially:

* changing hosts-file
* set up hooks
* ..

**Comment by coorasse** [comment]
make the idea more concrete and a detailed list of improvements to do.

**Comment by Kjir** [comment]
So would I have to type `yes` or `no` every time I run the `bin/setup`? That would be quite inconvenient...

Also you would then need some way of setting up the project that works for the CI and for the staging/production servers, without requiring user input

**Comment by sihu** [comment]
but the cases i have in my mind are exactly things you don't want to do on your CI. and we could easily skip them on the ci

**Comment by coorasse** [comment]
The current `bin/setup` shouldn't be run on the CI either. But I think it should be updated in order to support it.

**Comment by coorasse** [comment]
I think the current `bin/setup` doesn't do anything on a system level anymore. Can we close this issue?

**Comment by macav** [comment]
i noticed that `bin/setup` still installs pre-push hooks.. this is bothering me quite a bit.. can we get rid of it and make this step optional?

**Comment by coorasse** [comment]
I am fine with that proposal @macav, we should discuss that.

**Comment by coorasse** [comment]
Closing for lack of feedback
