### ISSUE TITLE
Sentry with Heroku

### ISSUE THREAD

**Issue by sihu** [renuo/applications-setup-guide#97]
```
WARN -- sentry: ** [Raven] You are running on Heroku but haven't enabled Dyno Metadata. 
For Sentry's release detection to work correctly, please run
 `heroku labs:enable runtime-dyno-metadata`
```

Is this always necessary and could be integrated in the setup guide?

**Comment by coorasse** [comment]
Where do we see this @sihu ?

**Comment by macav** [comment]
@coorasse it shows up when you open rails console on Heroku
![image](https://user-images.githubusercontent.com/3784696/49089457-e56ef500-f25b-11e8-87de-a3a02b903dcd.png)

**Comment by coorasse** [comment]
I see. It would be probably smart to enable it on our projects. I will update the renuo-cli script to enable it if you guys agree

**Comment by coorasse** [comment]
See https://github.com/renuo/renuo-cli/pull/52

**Comment by coorasse** [comment]
I added it to the renuo-cli and to all our projects.
